- hosts: all
  become: yes 
  environment:
    GITHUB_API_TOKEN: <Github token>
    SLACK_API_TOKEN: <Slack token>
  tasks:
    - name: Install npm,nodejs,git
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
       - npm
       - nodejs-legacy
       - git
    - name: Update npm
      command: npm install npm@latest -g
    
    - name: Clone github repository
      git: repo=https://github.com/sridharswamy/ComBot dest=/home/vagrant/ComBot accept_hostkey=yes

    - name: Install npm packages
      npm: path=/home/vagrant/ComBot

    - name: Ensure Redis is present
      apt: pkg=redis-server state=latest

    - name: Ensure Redis is started
      service: name=redis-server state=started enabled=yes
    - name: Install forever
      npm: name=forever state=latest global=yes
    
    - name: Run Bot
      command: forever start index.js  chdir=/home/vagrant/ComBot

